apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openshift-monitoring-cr-controller
    app.kubernetes.io/part-of: openshift-monitoring-cr-controller
    app.kubernetes.io/managed-by: kustomize
  name: manager-rolebinding-cluster-pvc
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role-cluster-pvc
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openshift-monitoring-cr-controller
    app.kubernetes.io/part-of: openshift-monitoring-cr-controller
    app.kubernetes.io/managed-by: kustomize
  name: manager-rolebinding-user-pvc
  namespace: openshift-user-workload-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role-user-pvc
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
